# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'author.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ario(object):
    def setupUi(self, Dialog_ario):
        Dialog_ario.setObjectName("Dialog_ario")
        Dialog_ario.resize(444, 176)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/yt_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_ario.setWindowIcon(icon)
        Dialog_ario.setModal(True)
        self.label = QtWidgets.QLabel(Dialog_ario)
        self.label.setGeometry(QtCore.QRect(90, 30, 271, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/ario_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_ario)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_ario)
        self.label_3.setGeometry(QtCore.QRect(270, 150, 171, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog_ario)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ario)

    def retranslateUi(self, Dialog_ario):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ario.setWindowTitle(_translate("Dialog_ario", "Author"))
        self.label_2.setText(_translate("Dialog_ario", "Created By ARIONET35"))
        self.label_3.setText(_translate("Dialog_ario", "© Copyright 2023 Ario Bara Riski"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ario = QtWidgets.QDialog()
    ui = Ui_Dialog_ario()
    ui.setupUi(Dialog_ario)
    Dialog_ario.show()
    sys.exit(app.exec_())
